### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by AsGreyWolf** [gsmcmullin/atom-gdb-debugger#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.11
**OS**: linux 4.12.8-2-ARCH
**Thrown From**: [atom-gdb-debugger](https://github.com/gsmcmullin/atom-gdb-debugger) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /home/asgreywolf/.atom/packages/atom-gdb-debugger/lib/editor-integration.coffee:78

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at EditorIntegration.module.exports.EditorIntegration._toggleBreakpoint (/packages/atom-gdb-debugger/lib/editor-integration.coffee:78:27)
    at /packages/atom-gdb-debugger/lib/editor-integration.coffee:1:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:265:29)
    at /usr/lib/atom/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:606:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:397:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:100:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:59)
```

### Commands

```
     -6:59.6.0 intentions:highlight (input.hidden-input)
     -6:59.1.0 window:toggle-dev-tools (input.hidden-input)
     -3:51 intentions:highlight (input.hidden-input)
     -3:50.6.0 command-palette:toggle (input.hidden-input)
  3x -3:49.6.0 core:backspace (input.hidden-input)
     -3:46.9.0 core:confirm (input.hidden-input)
     -3:46.9.0 settings-view:core (input.hidden-input)
  2x -3:33.8.0 core:confirm (input.hidden-input)
  3x -1:18.9.0 atom-gdb-debugger:connect (input.hidden-input)
     -0:26.9.0 intentions:highlight (input.hidden-input)
     -0:26 command-palette:toggle (input.hidden-input)
     -0:24.7.0 core:confirm (input.hidden-input)
     -0:24.7.0 settings-view:core (input.hidden-input)
     -0:21.9.0 core:backspace (input.hidden-input)
     -0:21.2.0 core:confirm (input.hidden-input)
     -0:08.0 atom-gdb-debugger:toggle-breakpoint (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
activate-power-mode-delete 0.6.1 
atom-beautify 0.30.5 
atom-gdb-debugger 0.2.2 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-polymer 0.13.0 
autoclose-html 0.23.0 
autocomplete-clang 0.11.3 
autocomplete-glsl 0.2.3 
autocomplete-java 1.2.7 
autocomplete-oracle 1.2.0 
autocomplete-python 1.10.1 
autoprefixer 3.7.1 
build 0.68.0 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
clang-format 1.29.0 
color-picker 2.2.5 
convert-to-utf8 0.2.4 
csscomb 0.3.1 
dbg 1.6.1 
dbg-gdb 1.7.6 
docblockr 0.11.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 7.9.3 
git-projects 1.17.0 
git-time-machine 1.5.9 
github-issues 0.9.0 
graphviz-preview-plus 1.4.4 
Hydrogen 1.20.0 
hydrogen-xdbg 0.0.4 
imdone-atom 2.2.6 
imdone-atom-github 0.1.11 
intentions 1.1.5 
javascript-snippets 1.2.1 
jshint 1.8.6 
language-d 3.3.1 
language-dot 1.7.0 
language-glsl 2.0.1 
language-matlab 0.2.1 
language-opencl 0.1.1 
language-oracle 1.8.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-cppcheck 0.2.3 
linter-csslint 1.3.4 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-opencl 1.0.2 
linter-polymer 0.0.3 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.5 
linter-write-good 0.9.0 
minimap 4.29.6 
minimap-git-diff 4.3.1 
minimap-linter 2.0.2 
minimap-split-diff 0.3.7 
output-panel 0.3.4 
platformio-ide-terminal 2.5.5 
python-jedi 0.3.8 
script 3.15.0 
split-diff 1.4.3 
symbols-tree-view 0.14.0 
sync-settings 0.8.2 
tree-view-git-status 1.4.0 
```

**Comment by mbmcavoy** [comment]
I am having the same issue. Steps to reproduce:
Right-click on line of code, choose Toggle Breakpoint.

I had used this successfully a few months ago, but haven't been using Atom. I'm not 100% sure, but I'm thinking that it had been possible to click next the the line numbers to toggle breakpoints as well, but nothing happens and there doesn't seem to be space for an indicator.

**Comment by gsmcmullin** [comment]
Fixed in 7a4de67d744a5c51a619df6c7801d1d571e1b6bf

**Comment by vyaduvanshi** [comment]
I'm facing the same error. Am I doing something wrong ?

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-gdb-debugger](https://github.com/gsmcmullin/atom-gdb-debugger) package 0.2.2


### Stack Trace

Uncaught TypeError: Cannot read property 'editorElement' of undefined

```
At C:\Users\zZE\.atom\packages\atom-gdb-debugger\lib\editor-integration.coffee:7

TypeError: Cannot read property 'editorElement' of undefined
    at posFromMouse (/packages/atom-gdb-debugger/lib/editor-integration.coffee:7:16)
    at EditorIntegration.module.exports.EditorIntegration._toggleBreakpoint (/packages/atom-gdb-debugger/lib/editor-integration.coffee:76:21)
    at /packages/atom-gdb-debugger/lib/editor-integration.coffee:1:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.1/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.28.1/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.28.1/resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.28.1/resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  2x -3:19.8.0 atom-gdb-debugger:connect (input.hidden-input)
  3x -2:54.9.0 core:move-up (input.hidden-input)
  3x -2:54 core:move-down (input.hidden-input)
  3x -2:53.1.0 core:move-up (input.hidden-input)
     -2:49.6.0 atom-gdb-debugger:toggle-breakpoint (input.hidden-input)
     -2:39.1.0 atom-gdb-debugger:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:38 atom-gdb-debugger:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:35.2.0 atom-gdb-debugger:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:34.2.0 atom-gdb-debugger:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:32.9.0 atom-gdb-debugger:configure (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  6x -2:27.4.0 atom-gdb-debugger:continue (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:40.8.0 atom-gdb-debugger:next (input.hidden-input)
     -1:39 atom-gdb-debugger:step (input.hidden-input)
     -1:37.8.0 atom-gdb-debugger:continue (input.hidden-input)
     -1:37.3.0 atom-gdb-debugger:next (input.hidden-input)
  2x -1:36.1.0 atom-gdb-debugger:toggle-breakpoint (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-gdb-debugger 0.2.2 
autocomplete-clang 0.11.5 
busy-signal 1.4.3 
dbg 1.6.3 
dbg-gdb 1.7.8 
file-icons 2.1.22 
gcc-make-run 0.2.12 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.2.0 
linter-clang 4.1.2 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
output-panel 0.3.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.3 
```

**Comment by Dan-Knox** [comment]
This is also happening to me. I just installed the latest version now and confirmed that the changes from the commit referenced above are indeed present.

Any other suggestions? This plugin looks quite useful. Thanks for all your hard work. Let me know if you need anything from me.

**Comment by Dan-Knox** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04.1
**Thrown From**: [atom-gdb-debugger](https://github.com/gsmcmullin/atom-gdb-debugger) package 0.2.2


### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /home/dknox/.atom/packages/atom-gdb-debugger/lib/editor-integration.coffee:78

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at EditorIntegration.module.exports.EditorIntegration._toggleBreakpoint (/packages/atom-gdb-debugger/lib/editor-integration.coffee:78:27)
    at /packages/atom-gdb-debugger/lib/editor-integration.coffee:1:1)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  4x -9:37.2.0 memory-bro:toggle (input.hidden-input)
     -9:33.4.0 pane:show-previous-item (input.hidden-input)
  3x -9:32.2.0 pane:show-next-item (input.hidden-input)
     -9:25.9.0 vim-mode-plus:move-down (input.hidden-input)
     -9:25.3.0 intentions:highlight (input.hidden-input)
  2x -9:24.9.0 memory-bro:toggle (input.hidden-input)
  2x -9:16.8.0 vim-mode-plus:move-up (input.hidden-input)
     -9:15.3.0 intentions:highlight (input.hidden-input)
     -9:13.5.0 vim-mode-plus:scroll-half-screen-down (input.hidden-input)
     -9:11.9.0 vim-mode-plus:scroll-half-screen-up (input.hidden-input)
     -8:51.2.0 intentions:highlight (input.hidden-input)
     -8:50.7.0 settings-view:open (input.hidden-input)
  2x -7:06.5.0 atom-gdb-debugger:connect (input.hidden-input)
     -6:00.6.0 atom-gdb-debugger:configure (atom-workspace.workspace.scrollbars-visible-always.theme-chester-atom-syntax.theme-one-dark-ui)
     -5:57.4.0 atom-gdb-debugger:connect (atom-workspace.workspace.scrollbars-visible-always.theme-chester-atom-syntax.theme-one-dark-ui)
     -5:19 atom-gdb-debugger:toggle-breakpoint (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
an-old-hope-syntax 1.0.4 
atom-gdb-debugger 0.2.2 
atom-ide-debugger-native-gdb 0.7.3 
atomic-rtags 1.3.0 
autocomplete-clang 0.11.5 
autocomplete-ctags 0.4.1 
autocomplete-lua 0.9.1 
build 0.70.0 
busy-signal 1.4.3 
chester-atom-syntax 0.3.2 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
eval-and-replace 1.2.0 
ex-mode 0.18.0 
file-icons 2.1.27 
gpp-compiler 3.0.7 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
language-docker 1.1.8 
language-ini 1.20.0 
language-lua 0.9.11 
language-pgsql 0.2.3 
language-valgrind 0.1.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-gcc 0.7.1 
linter-lua 1.0.4 
linter-ui-default 1.7.1 
mc-dark-syntax 1.8.3 
memory-bro 2.1.0 
monokai 0.24.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
ruby-test-switcher 1.2.3 
seti-syntax 1.2.0 
styri-syntax 1.0.0 
switch-header-source 0.32.0 
tab-switcher 1.5.6 
tool-bar 1.1.11 
valign 1.1.3 
vim-mode-plus 1.34.0 
vim-mode-plus-ex-mode 0.11.0 
wakatime 7.0.7 
```

**Comment by alissonpelizaro** [comment]
Same issue on Ubuntu 18.04
Atom 1.43.0

**Comment by zzqDeco** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Deepin 15.11
**Thrown From**: [atom-gdb-debugger](https://github.com/gsmcmullin/atom-gdb-debugger) package 0.2.2


### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /home/zzqdeco/.atom/packages/atom-gdb-debugger/lib/editor-integration.coffee:78

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at EditorIntegration.module.exports.EditorIntegration._toggleBreakpoint (/packages/atom-gdb-debugger/lib/editor-integration.coffee:78:28)
    at /packages/atom-gdb-debugger/lib/editor-integration.coffee:1:1)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349385)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1252387)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1248521)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284591)
```

### Commands

```
     -6:48.1.0 core:paste (input.hidden-input)
     -6:47.6.0 core:confirm (input.hidden-input)
 17x -6:46.5.0 core:move-left (input.hidden-input)
 14x -6:44.9.0 core:backspace (input.hidden-input)
     -6:43.7.0 core:confirm (input.hidden-input)
     -5:51.3.0 core:backspace (input.hidden-input)
     -5:50.4.0 core:confirm (input.hidden-input)
  4x -3:18.2.0 atom-gdb-debugger:connect (input.hidden-input)
     -2:39.6.0 atom-gdb-debugger:continue (input.hidden-input)
  2x -2:37.4.0 atom-gdb-debugger:toggle-breakpoint (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-debugger 0.1.6 
atom-gdb-debugger 0.2.2 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-simplified-chinese-menu 0.6.5 
dbg 1.6.3 
dbg-gdb 1.7.8 
gcc-make-run 0.2.12 
highlight-selected 0.17.0 
linter 2.3.1 
linter-gcc 0.9.0 
linter-markdown 5.2.11 
linter-ui-default 1.8.1 
markdown-writer 2.11.9 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
output-panel 0.3.4 
pp-markdown 0.0.2 
rain-syntax 2.1.2 
```

**Comment by RabbitsAndAstronauts** [comment]
[Enter steps to reproduce:]

1. press f9 to set breakpoint

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Pop!_OS 20.04
**Thrown From**: [atom-gdb-debugger](https://github.com/gsmcmullin/atom-gdb-debugger) package 0.2.2


### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /home/heartbeast/.atom/packages/atom-gdb-debugger/lib/editor-integration.coffee:78

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at EditorIntegration.module.exports.EditorIntegration._toggleBreakpoint (/packages/atom-gdb-debugger/lib/editor-integration.coffee:78:28)
    at /packages/atom-gdb-debugger/lib/editor-integration.coffee:1:1)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350343)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1212051)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1208185)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284840)
```

### Commands

```
     -8:51.3.0 core:undo (input.hidden-input)
     -8:47.2.0 pane:show-next-item (input.hidden-input)
  2x -8:45 editor:toggle-line-comments (input.hidden-input)
  4x -7:58 core:move-left (input.hidden-input)
  4x -7:55.9.0 core:move-right (input.hidden-input)
     -7:54.1.0 core:move-left (input.hidden-input)
     -7:53.7.0 core:move-right (input.hidden-input)
  2x -7:52.6.0 core:backspace (input.hidden-input)
     -7:51.6.0 core:move-down (input.hidden-input)
  2x -7:50.4.0 core:backspace (input.hidden-input)
  2x -7:46.5.0 core:move-right (input.hidden-input)
  4x -7:15.9.0 core:undo (input.hidden-input)
  4x -3:10.4.0 core:move-down (input.hidden-input)
     -3:06.9.0 atom-gdb-debugger:toggle-breakpoint (input.hidden-input)
     -3:02.9.0 core:move-down (input.hidden-input)
     -2:59.5.0 atom-gdb-debugger:toggle-breakpoint (input.hidden-input)
```

### Non-Core Packages

```
atom-bash 1.1.1 
atom-chai-snippets 0.3.0 
atom-gdb-debugger 0.2.2 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-mocha-snippets 0.8.0 
atomic-monokai-syntax 1.2.1 
autocomplete-crates 2.0.0 
dark-hue-syntax 0.1.1 
ide-c-cpp 0.1.0 
ide-ccls 0.3.0 
language-haskell 1.23.0 
language-openscad 0.4.3 
language-scala 1.1.10 
language-wast 1.4.1 
language-webassembly 1.2.0 
council-communism-syntax 0.0.1 
pinned-tabs 2.3.1 
restart-atom 0.2.0 
terminal-tab 0.6.0 
Warm-Dark-syntax 0.1.0 
```
